language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: precise

  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script: composer install --no-interaction --prefer-dist
script: vendor/bin/phpunit --testdox --color